//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Week17_NetworkDBProject_05052016.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TVNetworkShowsDBEntities1 : DbContext
    {
        public TVNetworkShowsDBEntities1()
            : base("name=TVNetworkShowsDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<vwRatings4OrLess> vwRatings4OrLess { get; set; }
        public virtual DbSet<vwRatingsAbove4> vwRatingsAbove4 { get; set; }
    }
}
