//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Week17_NetworkDBProject_05052016.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Show
    {
        public int ShowID { get; set; }
        public int NetworkID { get; set; }
        public string Title { get; set; }
        public string Genre { get; set; }
        public Nullable<decimal> Rating { get; set; }
        public string Photo { get; set; }
        public string Website { get; set; }
        public string Description { get; set; }
    
        public virtual Network Network { get; set; }
    }
}
